<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <AssemblyName>ADServices</AssemblyName>
    <RootNamespace>Pxtl.ADServices</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- Need dependencies copied in so they can be bundled up into the nuget package for PS5.1-->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.5" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <Reference Include="System.DirectoryServices.Protocols" />
  </ItemGroup>
  <Target Name="CopyDebugToModuleRoot" AfterTargets="Build">
    <ItemGroup>
      <MySourceFiles Include="$(MSBuildProjectDirectory)\bin\$(Configuration)\**\*.*" />
    </ItemGroup>
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\ADServices.PSModule\ADServices\bin\netstandard2.0"/>
    <Copy SourceFiles="@(MySourceFiles)" DestinationFolder="$(MSBuildProjectDirectory)\..\ADServices.PSModule\ADServices\bin\%(RecursiveDir)" SkipUnchangedFiles="false" />
    <Message Text="Copying debug output to '$(MSBuildProjectDirectory)\..\ADServices.PSModule\ADServices\bin\'" />
  </Target>
</Project>
