<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <AssemblyName>ADServices</AssemblyName>
    <RootNamespace>Pxtl.ADServices</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.5.ReferenceAssemblies" Version="1.1.0" />
    <Reference Include="System.DirectoryServices.Protocols" />
  </ItemGroup>
  <ItemGroup>
    <MySourceFiles Include="$(MSBuildProjectDirectory)\bin\$(Configuration)\**\*.*" />
    <MyOutputFiles Include="$(MSBuildProjectDirectory)\..\bin\**\*.*" />
  </ItemGroup>
  <Target Name="CopyDebugToModuleRoot" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Copy SourceFiles="@(MySourceFiles)" DestinationFolder="$(MSBuildProjectDirectory)\..\bin\%(RecursiveDir)" SkipUnchangedFiles="false" />
    <Message Text="Copying debug output to '$(MSBuildProjectDirectory)\..\bin\'" />
  </Target>
  <Target Name="CopyReleaseToModuleRoot" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Delete Files="@(MyOutputFiles)" />
    <Copy SourceFiles="@(MySourceFiles)" DestinationFolder="$(MSBuildProjectDirectory)\..\bin\%(RecursiveDir)" SkipUnchangedFiles="false" />
    <Message Text="Copying release output to '$(MSBuildProjectDirectory)\..\bin\'" />
  </Target>
</Project>
