@(
    'CN=Enterprise Admins,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Print Operators,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Users,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Guests,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=IIS_IUSRS,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Event Log Readers,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Domain Controllers,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=RAS and IAS Servers,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Network Configuration Operators,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Terminal Server License Servers,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Domain Computers,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Enterprise Read-only Domain Controllers,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Pre-Windows 2000 Compatible Access,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Distributed COM Users,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Performance Monitor Users,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Replicator,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Denied RODC Password Replication Group,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Windows Authorization Access Group,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Administrators,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=DnsAdmins,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Backup Operators,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Domain Admins,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Read-only Domain Controllers,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Cryptographic Operators,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Server Operators,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Domain Guests,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Performance Log Users,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Group Policy Creator Owners,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Certificate Service DCOM Access,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Cert Publishers,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Allowed RODC Password Replication Group,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Schema Admins,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Protected Users,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Incoming Forest Trust Builders,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Remote Desktop Users,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=Account Operators,CN=Builtin,DC=samdom,DC=example,DC=com'
    'CN=DnsUpdateProxy,CN=Users,DC=samdom,DC=example,DC=com'
    'CN=Domain Users,CN=Users,DC=samdom,DC=example,DC=com'
)